/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.obarra.accurate.algorithm;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertEquals(6L, classUnderTest.getMinorAddedPath());
    }
}
