/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.obarra.accurate.algorithm;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {

    @Test
    void getMinorAddedPathWhenMinorPathIsInTheThreadRow() {
        Library classUnderTest = new Library();
        int [][] matrix = {{1, 2, 9},{2, 10, 3},{1, 1, 1}};
        long [] result = {1, 1, 1, 3};
        assertArrayEquals(result, classUnderTest.getMinorAddedPath(matrix));
    }

    @Test
    void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        int [][] matrix = {{1, 2, 9},{2, 5, 3},{5, 1, 5}};
        long [] result = {1, 2, 3, 6};
        assertArrayEquals(result, classUnderTest.getMinorAddedPath(matrix));
    }
}
