/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package alg

object Words {
    fun longestWord(sentence: String): String {
        return sentence.split(" ").maxBy { it.length } ?: ""
    }

    fun longestWordWithReduce(sentence: String): String {
        return sentence.split(" ").reduce { acc, next ->  if (acc.length >= next.length ) acc else next}
    }
}
